"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my honor, Angela Liu, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: yl42556
"""


class Node:
    """
    A modified version of the Node class for linked lists (using proper class
    coding practices). Instead of a data instance variable, this node class has both
    a coefficient and an exponent instance variable, which is used to represent each
    term in a polynomial.
    """

    def __init__(self, coeff, exp, link=None):
        """
        Node Constructor for polynomial linked lists.

        Args:
        - coeff: The coefficient of the term.
        - exp: The exponent of the term.
        - link: The next node in the linked list.
        """
        self.coeff = coeff
        self.exp = exp
        self.next = link

    @property
    def coeff(self):
        """
        Getter method for the coefficient attribute.
        """
        return self.__coeff

    @coeff.setter
    def coeff(self, value):
        """
        Setter method for the coefficient attribute.
        """
        if value is None or isinstance(value, int):
            self.__coeff = value
        else:
            raise ValueError("Coefficient must be an integer or None.")

    @property
    def exp(self):
        """
        Getter method for the exponent attribute.
        """
        return self.__exp

    @exp.setter
    def exp(self, value):
        """
        Setter method for the exponent attribute.
        """
        if value is None or isinstance(value, int):
            self.__exp = value
        else:
            raise ValueError("Exponent must be an integer or None.")

    @property
    def next(self):
        """
        Getter method for the next attribute.
        """
        return self.__next

    @next.setter
    def next(self, value):
        """
        Setter method for the next attribute.
        """
        if value is None or isinstance(value, Node):
            self.__next = value
        else:
            raise ValueError("Next must be a Node instance or None.")

    def __str__(self):
        """
        String representation of each term in a polynomial linked list.
        """
        return f"({self.coeff}, {self.exp})"


class LinkedList:
    '''
    Polynomial represented as Linked List
    '''
    def __init__(self):
        # You are also welcome to use a sentinel/dummy node!
        # It is definitely recommended, which will we learn more
        # about in class on Monday 3/24. If you choose to use
        # a dummy node, comment out the self.head = None
        # and comment in the below line. We use None to make sure
        # if there is an error where you accidentally include the
        # dummy node in your calculation, it will throw an error.
        self.dummy = Node(None, None)
        # self.head = None

    # Insert the term with the coefficient coeff and exponent exp into the polynomial.
    # If a term with that exponent already exists, add the coefficients together.
    # You must keep the terms in descending order by exponent.
    def insert_term(self, coeff, exp):
        '''
        Insert new term into polynomial
        '''
        if coeff == 0:
            return
        new_term = Node(coeff, exp)
        curr_term = self.dummy.next
        prev = self.dummy
        while curr_term is not None:
            # same exp
            if exp == curr_term.exp:
                curr_term.coeff += coeff
                if curr_term.coeff == 0:
                    prev.next = curr_term.next
                return
            # keep descend order
            if exp > curr_term.exp:
                prev.next = new_term
                new_term.next = curr_term
                return
            prev = curr_term
            curr_term = curr_term.next
        prev.next = new_term
        return

    def add(self, p):
        '''
        Add a polynomial with polynomial p

        Return
        ------
        LinkedList: new_ll
        '''
        self_val = self.dummy.next
        p_val = p.dummy.next
        new_ll = LinkedList()
        # when both are empty
        if self_val is None and p_val is None:
            return new_ll
        # add coeff when exp equal
        if self_val.exp == p_val.exp:
            new_val_coeff = self_val.coeff + p_val.coeff
            new_ll.insert_term(new_val_coeff, self_val.exp)
            return new_ll
        new_ll.insert_term(self_val.coeff, self_val.exp)
        new_ll.insert_term(p_val.coeff, p_val.exp)
        return new_ll

    def mult(self, p):
        '''
        Multiply a polynomial with polynomial p

        Return
        ------
        LinkedList: new_ll
        '''
        self_term_curr = self.dummy.next
        p_term_curr = p.dummy.next
        new_ll = LinkedList()
        if self_term_curr == 0 or p_term_curr == 0:
            return new_ll
        while self_term_curr:
            while p_term_curr:
                new_term_coeff = self_term_curr.coeff * p_term_curr.coeff
                new_term_exp = self_term_curr.exp + p_term_curr.exp
                new_ll.insert_term(new_term_coeff, new_term_exp)
                p_term_curr = p_term_curr.next
            self_term_curr = self_term_curr.next
            p_term_curr = p.dummy.next
        return new_ll

    # Return a string representation of the polynomial.
    def __str__(self):
        output = []
        curr_term = self.dummy.next
        while curr_term:
            if curr_term.next is None:
                output.append(str(curr_term))
            else:
                output.append(str(curr_term) + " + ")
            curr_term = curr_term.next
        return "".join(output)

def main():
    '''
    Read from stdin to create polynomial. Then calculate both's sum and product.
    '''
    frequency_p = int(input())
    poly_p = LinkedList()
    poly_q = LinkedList()
    # create p
    for _ in range(frequency_p):
        term_p = input().split()
        poly_p.insert_term(int(term_p[0]), int(term_p[1]))
    # create q
    input()
    frequency_q = int(input())
    for _ in range(frequency_q):
        term_q = input().split()
        poly_q.insert_term(int(term_q[0]), int(term_q[1]))
    # get sum of both & print
    print(poly_p.add(poly_q))
    # get product of both & print
    print(poly_p.mult(poly_q))

if __name__ == "__main__":
    main()
