"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my honor, Angela Liu, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: yl42556
"""

def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    longest_substr = 0
    for n in range(len(s)):
        freq_list = [0] * 256
        for m in (range(n, len(s))):
            freq_list[ord(s[m])] += 1
            sub_str = s[n:m+1]
            if len(sub_str) > longest_substr and max(freq_list) <= 1:
                longest_substr = len(sub_str)
    return longest_substr


def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    longest_substr = 0
    for n in range(len(s)):
        freq_list = [0] * 256
        for m in (range(n, len(s))):
            freq_list[ord(s[m])] += 1
            if freq_list[ord(s[m])] > 1:
                break
            current_length = m - n + 1
            if current_length > longest_substr:
                longest_substr = current_length
    return longest_substr


def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    seen = set()
    longest_substr = 0
    start = 0
    for end, char in enumerate(s):
        if char not in seen:
            seen.add(char)
        else:
            while not s[start] == s[end]:
                seen.remove(s[start])
                start += 1
            start += 1
        current_len = len(seen)
        if current_len > longest_substr:
            longest_substr = current_len
    return longest_substr
